url: https://core.easyscience.software
title: The building blocks for the easyScience universe
description: >-
  easyCore is the foundation of the easyScience universe, providing the building
  blocks for libraries and applications which make scientific data simulation
  and analysis easier.
